server:
  port: 8001
spring:
  #  application:
  #    name: hailtaxi-gateway
  main:
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      routes:
        - id: hailtaxi-driver
          uri: lb://hailtaxi-driver
          predicates:
            - Path=/driver/**
        - id: hailtaxi-order
          uri: lb://hailtaxi-order
          predicates:
            - Path=/order/**